package com.etiquette.User;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.etiquette.GlobalExceptionHandler.GlobalExceptionHandler;

@Controller // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class UserController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody ResponseEntity<?> addNewUser (@RequestBody AddUserFormDto addUserForm) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    User n = new User();

    n.setFirstName(addUserForm.firstname);
    n.setLastName(addUserForm.lastname);
    n.setEmail(addUserForm.email);
    n.setPassword(addUserForm.password);

    if (userRepository.findByEmail(addUserForm.email).isPresent()) {
      ResponseEntity<?> exceptionHandler = new GlobalExceptionHandler().handleEntityAlreadyExists("Email already exists");
      return exceptionHandler;
    } else {
      userRepository.save(n);
      ResponseEntity<?> exceptionHandler = new GlobalExceptionHandler().handleSuccesfullRequest("User added", null);
      return exceptionHandler;
    }
    
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }

  @GetMapping(path="/one")
  public @ResponseBody ResponseEntity<?>  getOneUser(@RequestParam Integer id) {
    Optional<User> user = userRepository.findById(id);
    if (user.isEmpty()) {
      ResponseEntity<?> exceptionHandler = new GlobalExceptionHandler().handleEntityNotFound("User not found");
      return exceptionHandler;
    } else {
      User finalUser = new User();
      finalUser.setId(id);
      finalUser.setFirstName(user.get().getFirstName());
      finalUser.setLastName(user.get().getLastName());
      finalUser.setEmail(user.get().getEmail());
      finalUser.setPassword(user.get().getPassword());
      ResponseEntity<?> exceptionHandler = new GlobalExceptionHandler().handleSuccesfullRequest("User found", finalUser);
      return exceptionHandler;
    }
  }

  @DeleteMapping(path="/delete")
  public @ResponseBody ResponseEntity<?> deleteUser (@RequestParam Integer id) {
    if (!userRepository.existsById(id)) {
      ResponseEntity<?> exceptionHandler = new GlobalExceptionHandler().handleEntityNotFound("User not found");
      return exceptionHandler;
    } else {
      userRepository.deleteById(id);
      ResponseEntity<?> exceptionHandler = new GlobalExceptionHandler().handleSuccesfullRequest("User deleted", null);
      return exceptionHandler;
    }
  }

  @PutMapping(path="/update")
  public @ResponseBody ResponseEntity<?> updateUser (@RequestParam Integer id, @RequestBody AddUserFormDto addUserForm) {
    if (!userRepository.existsById(id)) {
      ResponseEntity<?> exceptionHandler = new GlobalExceptionHandler().handleEntityNotFound("User not found");
      return exceptionHandler;
    } else {
      User user = new User();

      user.setId(id);
      user.setFirstName(addUserForm.firstname);
      user.setLastName(addUserForm.lastname);
      user.setEmail(addUserForm.email);
      user.setPassword(addUserForm.password);

      userRepository.save(user);

      ResponseEntity<?> exceptionHandler = new GlobalExceptionHandler().handleSuccesfullRequest("User updated", user);
      return exceptionHandler;
    }
  }
}